import React, { useState } from "react";
import Head from "next/dist/shared/lib/head";
import { BasicInfo } from "./BasicInfo";
import { HigherEducation } from "./HigherEducation";
import { WorkExperience } from "./WorkExperience";
import { ContactInfo } from "./ContactInfo";
import styles from "../../styles/Home.module.css";
import { Formik, Form, Field, FieldArray } from "formik";
const RegisterForm = () => {
  // const activeIndex = useSelector((state) => state.registerReducer.activeIndex);
  const [activeIndex, setActiveIndex] = useState(1);

  return (
    <div className={styles.container}>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3 className="">Sign Up</h3>
      {/* <div className="form-parent-box">
        <BasicInfo />
        <HigherEducation />
        <WorkExperience />
        <ContactInfo />
      </div> */}

      <Formik
        initialValues={{
          firstName: "",
          lastName: "",
          email: "",
          yearOfGraduation: "",
          course: "",
          twitterHandle: "",
          linkedinHandle: "",
          examsCleared: [
            {
              nameOfExam: "",
              rank: -1,
              year: -1,
            },
          ],
          higherEducation: [
            {
              course: "",
              yearOfGraduation: 0,
              institute: "",
            },
          ],
          workExperience: [
            {
              currentOrg: -1,
              type: "",
              experience: "",
              organisation: "",
              profile: "",
            },
          ],
        }}
        onSubmit={(values, { setSubmitting }) => {
          console.log(values);
        }}
      >
        {(props) => (
          <Form onSubmit={props.handleSubmit}>
            <Field
              className="form-control"
              type="text"
              name="firstName"
              placeholder="First Name"
              value={props.values.firstName}
              onChange={props.handleChange}
            />
            <Field
              className="form-control"
              type="text"
              name="lastName"
              placeholder="Last Name"
              value={props.values.lastName}
              onChange={props.handleChange}
            />
            <Field
              className="form-control"
              type="text"
              name="course"
              placeholder="Course"
              value={props.values.course}
              onChange={props.handleChange}
            />
            <Field
              className="form-control"
              type="year"
              name="yearOfGraduation"
              placeholder="Year of Graduation"
              value={props.values.yearOfGraduation}
              onChange={props.handleChange}
            />
            <Field
              className="form-control"
              type="email"
              name="email"
              placeholder="Email"
              onChange={props.handleChange}
              value={props.values.email}
            />
            <br />
            <button
              type="submit"
              className="btn btn-danger"
              onClick={() => {
                // dispatch(setActiveIndex(-1));
              }}
            >
              Previous
            </button>
            <button
              type="submit"
              className="btn btn-danger"
              onClick={() => {
                // dispatch(setActiveIndex(1));
              }}
            >
              Next
            </button>
          </Form>
        )}
      </Formik>
    </div>
  );
};

export default RegisterForm;
