import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Login } from "../components/Login";

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.nav2}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>People</li>
          <li>Sign In</li>
        </ul>
      </div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Alumni Page of ANDC
        </h1>
      <Login />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
